### ISSUE TITLE
Getting ERR_MODULE_NOT_FOUND error with latest nth-check version 2.1.0 when using ESM

### ISSUE THREAD

**Issue by dtempx** [fb55/nth-check#209]
Getting the following error with latest nth-check 2.1.0 when running with ESM and Node v14.13.3...
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'test\node_modules\nth-check\lib\esm\parse' imported from test\node_modules\nth-check\lib\esm\index.js
    at new NodeError (internal/errors.js:322:7)←[39m
    at finalizeResolution (internal/modules/esm/resolve.js:318:11)←[39m
    at moduleResolve (internal/modules/esm/resolve.js:776:10)←[39m
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)←[39m
    at Loader.resolve (internal/modules/esm/loader.js:89:40)←[39m
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)←[39m
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)←[39m
    at link (internal/modules/esm/module_job.js:75:36)←[39m {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
For my case `nth-check` is a dependency brought in via `cheerio ^1.0.0-rc.10`

### Current contents of node_modules\nth-check\lib\esm\index.js in version 2.1.0...
```js
import { parse } from "./parse";
import { compile, generate } from "./compile";
export { parse, compile, generate };
```
> Don't parse and compile imports need to explicitly specify the .js extension to work under ESM? (correct me if wrong)

### Previous contents of node_modules\nth-check\lib\index.js in version 2.0.1...
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.compile = exports.parse = void 0;
var parse_1 = require("./parse");
Object.defineProperty(exports, "parse", { enumerable: true, get: function () { return parse_1.parse; } });
var compile_1 = require("./compile");
Object.defineProperty(exports, "compile", { enumerable: true, get: function () { return compile_1.compile; } });
```

**Comment by jaywcjlove** [comment]
@dtempx This is the same problem as #208.
